# Permalinks
permalink:           pretty

markdown:      maruku

# Setup
title:               Shuhui Dong
tagline:             
url:                 http://shdong.github.io
shorturl:            blog.hwdong.com
paginate:            5
baseurl:             ""
excerpt_separator: <!--more-->  #global excerpt separator for the blog posts

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Shuhui Dong
  url:               http://shdong.github.io
  email:             shuhuidong@gmail.com

# Custom vars
#version:             2.0.0
github:
  repo:              github.com/shdong/shdong.github.io

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

pages_list:       
  About: '/about'
  Archive: '/archive' 
  #Feed: '/atom.xml'

  # Duoshuo settings
duoshuo_username: shdong
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing
